apiVersion: v1
kind: ConfigMap
metadata:
  name: sso-frontend-nginx-conf
data:
  nginx.conf: |
    upstream Backend {
    # back_end_server will be replaced in docker
    server sso-backend;
    }

    server {

        location /static {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/;
        }

        location /api/ {
            proxy_pass http://Backend;
        }

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
